/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageAirlinerTA;

import Business.Airliner;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author riyamoitra
 */
public class AirLinerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AirLinerWorkAreaJPanel
     */
    
    private JPanel CardSequenceJPanel;
    private Airliner airliner;

    public AirLinerWorkAreaJPanel(JPanel CardSequenceJPanel ,Airliner airliner ){
        initComponents();
        this.CardSequenceJPanel= CardSequenceJPanel;
        this.airliner= airliner;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManageFlight = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        btnManageFlight.setText("Manage Flight >>");
        btnManageFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageFlightActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(btnManageFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(131, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(btnManageFlight)
                .addContainerGap(201, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageFlightActionPerformed
        // TODO add your handling code here:
        ManageFlightDirectoryJPanel mfdjp = new ManageFlightDirectoryJPanel(CardSequenceJPanel , airliner);
        CardSequenceJPanel.add("ManageFlightDirectoryJPanel", mfdjp);
        CardLayout layout = (CardLayout) CardSequenceJPanel.getLayout();
        layout.next(CardSequenceJPanel);
    }//GEN-LAST:event_btnManageFlightActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageFlight;
    // End of variables declaration//GEN-END:variables
}
