/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Patient;

import Business.Department.Department;
import Business.Doctor.Doctor;
import Business.Ecosystem;
import Business.Hospital.Hospital;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.PhysicianRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author riyamoitra
 */
public class PatientScheduleAppointmentJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientPageOneJPanel
     */
    
    private JPanel CardLayoutJPanel;
    private UserAccount account;
    private Ecosystem business;
    ArrayList <String> bookedSlot= new ArrayList();
    

    public PatientScheduleAppointmentJPanel(JPanel CardLayoutJPanel, UserAccount account, Ecosystem business) {

        initComponents();
        this.CardLayoutJPanel = CardLayoutJPanel;
        this.account=account;
        this.business = business;
        
        populateHopitalComboBox();

    }
    
    public void populateHopitalComboBox() {
        
        ArrayList<Hospital> hospitalList = business.getHospitalDirectory().getHospitalList();
        Hospital[] comboBoxModel1 = hospitalList.toArray(new Hospital[0]);
        
        
        hospitalNameComboBox.setModel(new DefaultComboBoxModel<Hospital>(comboBoxModel1));
        
    }
    
    public void populateTable(ArrayList<PhysicianRequest> appointments) {
        // populate all patients in patient directory
        
        int rowCount = jTable1.getRowCount();
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        for(int i=rowCount-1;i>=0;i--) {
            model.removeRow(i);
        }
        
        for(PhysicianRequest pr: appointments) {
            Object row[] = new Object[4];
            
            Doctor doctor = (Doctor) pr.getReceiver().getDetails();
            
            row[0] = doctor.getName();
            row[1] = doctor.getDepartment().getHospital().getName();
            row[2] = doctor.getDepartment().getDepartmentName();
            row[3] = pr.getTime();
            
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        physicianNameCombo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        searchByHospitalName = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        hospitalNameComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        departmentlNameCombo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        physicianNameCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                physicianNameComboActionPerformed(evt);
            }
        });
        add(physicianNameCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 160, -1));

        jLabel1.setText("Hospital: ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 55, 124, 27));

        searchByHospitalName.setText("Get available time slots");
        searchByHospitalName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByHospitalNameActionPerformed(evt);
            }
        });
        add(searchByHospitalName, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 246, 226, -1));

        jLabel2.setText("Physician");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 140, 124, 27));

        hospitalNameComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospitalNameComboBoxActionPerformed(evt);
            }
        });
        add(hospitalNameComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 56, 160, -1));

        jLabel3.setText("Department: ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 95, 124, 27));

        departmentlNameCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentlNameComboActionPerformed(evt);
            }
        });
        add(departmentlNameCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 95, 160, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Physician", "Hospital", "Department", "Time Slot"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 326, 560, 140));

        jLabel4.setText("Date");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 179, 124, 27));
        add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 150, -1));

        jButton1.setText("Book Now");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, -1, -1));

        backBtn.setText("<back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void physicianNameComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_physicianNameComboActionPerformed

    }//GEN-LAST:event_physicianNameComboActionPerformed

    private void searchByHospitalNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByHospitalNameActionPerformed
        // TODO add your handling code here:
        
        Hospital selectedHospital = (Hospital) hospitalNameComboBox.getSelectedItem();
        Department selectedDept = (Department) departmentlNameCombo.getSelectedItem();
        Doctor selectedDoctor = (Doctor) physicianNameCombo.getSelectedItem();
        Date selectedDate = jDateChooser1.getDate();
               
        if(selectedHospital == null || selectedDept == null || selectedDate == null) {
            JOptionPane.showMessageDialog(null, "Please select the hospital, departmnent and date");
            return;
        }
        
         if(selectedDate.before(new Date())) {
            JOptionPane.showMessageDialog(null, "Please select a valid date");
            return;
        }
        
        ArrayList<PhysicianRequest> availableWorkRequests = new ArrayList();
        
        if(selectedDoctor == null) {
            
            for(Doctor d: selectedDept.getDoctorDirectory()) {
                availableWorkRequests.addAll(this.getAvailablePhysicianSlots(d, selectedDate));
            }
          
        } else {
            
            availableWorkRequests = this.getAvailablePhysicianSlots(selectedDoctor, selectedDate);
            
        }
        
        populateTable(availableWorkRequests);
        

    }//GEN-LAST:event_searchByHospitalNameActionPerformed

    private void hospitalNameComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospitalNameComboBoxActionPerformed
        // TODO add your handling code here:
        
        Hospital selectedHospital = (Hospital) hospitalNameComboBox.getSelectedItem();
        
        ArrayList<Department> deptList = selectedHospital.getDepartmentDirectory();
        Department[] comboBoxModel = deptList.toArray(new Department[0]);
       
        departmentlNameCombo.setModel(new DefaultComboBoxModel<Department>(comboBoxModel));
     
    }//GEN-LAST:event_hospitalNameComboBoxActionPerformed

    private void departmentlNameComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentlNameComboActionPerformed
        // TODO add your handling code here:
        
        Department selectedDept = (Department) departmentlNameCombo.getSelectedItem();
        
        ArrayList<Doctor> doctorList = selectedDept.getDoctorDirectory();
        Doctor[] comboBoxModel2 = doctorList.toArray(new Doctor[0]);
        
        physicianNameCombo.setModel(new DefaultComboBoxModel<Doctor>(comboBoxModel2));
        
        
    }//GEN-LAST:event_departmentlNameComboActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = jTable1.getSelectedRow();
       
        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row");
            return;
        }
        
        Hospital selectedHospital = (Hospital) hospitalNameComboBox.getSelectedItem();
        Department selectedDept = (Department) departmentlNameCombo.getSelectedItem();
        Doctor selectedDoctor = (Doctor) physicianNameCombo.getSelectedItem();
        Date selectedDate = jDateChooser1.getDate();
        String timeSlot = (String) jTable1.getValueAt(selectedRow, 3);
        
        // bookedSlot.add(timeSlot);
        UserAccount doctorAccount = business.getUserAccountDirectory().getUserById(selectedDoctor.getDoctorId());
        
        PhysicianRequest request = new PhysicianRequest();
        request.setReceiver(doctorAccount);
        request.setSender(account);
        request.setRequestDate(new Date());
        request.setStatus("pending physician approval");
        request.setAppointmentDate(selectedDate);
        request.setTime(timeSlot);
        
        
        
        doctorAccount.getWorkQueue().getWorkRequestList().add(request);
        this.account.getWorkQueue().getWorkRequestList().add(request);
        
        JOptionPane.showMessageDialog(null, "Appointment sent for approval to physician");
        populateTable(new ArrayList());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        CardLayoutJPanel.remove(this);
        CardLayout layout = (CardLayout) CardLayoutJPanel.getLayout();
        layout.previous(CardLayoutJPanel);
    }//GEN-LAST:event_backBtnActionPerformed

    private ArrayList<PhysicianRequest> getAvailablePhysicianSlots (Doctor doctor, Date selectedDate) {
        ArrayList<PhysicianRequest> availableWorkRequests = new ArrayList();
        ArrayList<PhysicianRequest> unavailableWorkRequests = new ArrayList();

        ArrayList<WorkRequest> existingRequests = this.business.getUserAccountDirectory().getUserById(doctor.getDoctorId()).getWorkQueue().getWorkRequestList();
        for(WorkRequest w : existingRequests) {
            
            if(w.getStatus().equals("pending physician approval") || w.getStatus().equals("physician accepted")) {
                PhysicianRequest pr = (PhysicianRequest) w;
                if(pr.getAppointmentDate().getDate() == selectedDate.getDate()) {
                    unavailableWorkRequests.add(pr);
                }
            }
        }
        for(int time = 8; time < 19; time++) {
            boolean isValid = true;
            for(PhysicianRequest pr: unavailableWorkRequests) {
                if(pr.getTime().equals(time + " - " + (time + 1))) {
                    isValid = false;
                    break;
                }
            }
            if(isValid) {
                PhysicianRequest newRequest = new PhysicianRequest();
                newRequest.setReceiver(this.business.getUserAccountDirectory().getUserById(doctor.getDoctorId()));
                newRequest.setAppointmentDate(selectedDate);
                newRequest.setRequestDate(new Date());
                newRequest.setSender(account);
                newRequest.setTime(time + " - " + (time + 1));

                availableWorkRequests.add(newRequest);
            }
        }
        return availableWorkRequests;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JComboBox<Department> departmentlNameCombo;
    private javax.swing.JComboBox<Hospital> hospitalNameComboBox;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<Doctor> physicianNameCombo;
    private javax.swing.JButton searchByHospitalName;
    // End of variables declaration//GEN-END:variables
}
