/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SearchFlights;

import Business.Airliner;
import Business.AirlinerDirectory;
import Business.Customer;
import Business.Flight;
import Business.FlightDirectory;
import Business.Seat;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shivanivats
 */
public class FindFlights extends javax.swing.JPanel {
    
    private JPanel CardSequenceJPanel;
    private FlightDirectory flightDirectory;
    private AirlinerDirectory airlineDirectory;
    private Airliner airliner;
    private Customer customer;
    private Seat seat;

    /**
     * Creates new form FindFlights
     */
    public FindFlights(JPanel CardSequenceJPanel,AirlinerDirectory airlineDirectory,FlightDirectory flightDirectory, Customer customer, Seat seat ) {
        this.CardSequenceJPanel = CardSequenceJPanel;
        this.airlineDirectory = airlineDirectory;
        this.flightDirectory = flightDirectory;
        this.customer = customer;
        this.seat = seat;
        
        initComponents();
        // Commented as not required anymore.
//        populateAirlineCombo();
    }
    
    public void populateTable(ArrayList<Flight> a) {
        DefaultTableModel dtm = (DefaultTableModel) tblFlightDetails.getModel();
        dtm.setRowCount(0);
        
        for(Flight f : a){
            Object [] row = new Object[6];
            row[0] = f;
            row[1] = f.getAirlineName();
            row[2] = f.getSource();
            row[3] = f.getDestination();
            row[4] = f.getStartDate();
            
            row[5] = f.getPrice();
//            row[5] = f.getEndDate();
            dtm.addRow(row);
        }
    }
    // COmmented as not required anymore.
//    public void populateSourceCombo() {
//        comboBoxSource.removeAllItems();
//        
//        for(String ) {
//            
////        }
//    }
    
//    public void populateAirlineCombo()
//    {
//        airlineCombobox.removeAllItems();
//        
//        for (String s : airlineDirectory.getAirlineNames())
//                {
//                   airlineCombobox.addItem(s);
//                }
//    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblFlightDetails = new javax.swing.JTable();
        btnSearch = new javax.swing.JButton();
        txtFlightNumber = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        btnBookNow = new javax.swing.JButton();
        txtSource = new javax.swing.JTextField();
        txtDestination = new javax.swing.JTextField();
        txtAirliner = new javax.swing.JTextField();
        btnViewBookedTickets = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setBackground(new java.awt.Color(255, 255, 255));

        tblFlightDetails.setForeground(new java.awt.Color(0, 51, 102));
        tblFlightDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Flight No.", "Airliner Name", "Flying From", "Flying To", "Departing", "Price"
            }
        ));
        jScrollPane4.setViewportView(tblFlightDetails);

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });

        btnBookNow.setText("Book Now");
        btnBookNow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookNowActionPerformed(evt);
            }
        });

        txtDestination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDestinationActionPerformed(evt);
            }
        });

        btnViewBookedTickets.setText("View Booked Tickets");
        btnViewBookedTickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewBookedTicketsActionPerformed(evt);
            }
        });

        jLabel1.setText("Select Airline:");

        jLabel2.setText("From:");

        jLabel3.setText("To:");

        jLabel4.setText("Flight Number:");

        jLabel5.setText("Date:");

        jLabel6.setFont(new java.awt.Font("Lao Sangam MN", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 255));
        jLabel6.setText("Find Flights");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(123, 123, 123)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtFlightNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                            .addComponent(txtDate, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                            .addComponent(txtSource)
                            .addComponent(txtDestination, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAirliner, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearch)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnViewBookedTickets, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBookNow, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(326, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(txtAirliner, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(btnSearch))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFlightNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBookNow)
                    .addComponent(btnViewBookedTickets))
                .addContainerGap(236, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBookNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookNowActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblFlightDetails.getSelectedRow();
        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(null,"Please Select a row from table first to Book flight", "Warining", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Flight flight = (Flight) tblFlightDetails.getValueAt(selectedRow, 0);
        SeatingArrangementJPanel bookPanel = new SeatingArrangementJPanel(CardSequenceJPanel, flight,customer,seat);
        CardSequenceJPanel.add("BookingJPanel", bookPanel);
        CardLayout layout = (CardLayout) CardSequenceJPanel.getLayout();
        layout.next(CardSequenceJPanel);
    }//GEN-LAST:event_btnBookNowActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        
        ArrayList<Flight> temp = new ArrayList<>();
        ArrayList<Flight> flightList = new ArrayList<>();
        
        
        for (Airliner a : airlineDirectory.getAirlineList()){
            flightList.addAll(a.getFlightDirectory().getFlightList());
        }
        
        String airlinerName = txtAirliner.getText();
        if (!airlinerName.isEmpty()) {
            System.out.println(airlinerName);
            for(Flight a : flightList) {
                System.out.println(a.getAirlineName());
                if(a.getAirlineName().equals(airlinerName)) {
                    temp.add(a);
                }
            }
            flightList = temp;
        }
        String source = txtSource.getText();
        if (!source.isEmpty()) {
            temp = new ArrayList<>();
            for(Flight f : flightList) {
                if(f.getSource().equals(source)) {
                    temp.add(f);
                }
            }
            flightList = temp;
            
        }
        
        String destination = txtDestination.getText();
        if (!destination.isEmpty()) {
        temp = new ArrayList<>();
            for(Flight f : flightList) {
                if(f.getDestination().equals(destination)) {
                    temp.add(f);
                }
            }
            flightList = temp;
        }

        
        temp = new ArrayList<>();
        try {
            if(!txtFlightNumber.getText().isEmpty()) {
                int flightNumber = Integer.parseInt(txtFlightNumber.getText());
                for(Flight f : flightList) {
                    if(f.getFlightNumber() == flightNumber) {
                        temp.add(f);
                    }
                }
                flightList = temp;
            }
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null,"Flight Number should have integer value only");
            return;
        }
        
        temp = new ArrayList<>();
        if(!txtDate.getText().isEmpty()) {
            try {
                Date date = new SimpleDateFormat("dd/MM/yyyy").parse(txtDate.getText());
                for(Flight f : flightList) {
                    if(f.getStartDate().equals(date)) {
                        temp.add(f);
                    }
                }
                flightList = temp;
            } catch (Exception e) {
                System.out.println("Wrong format for Date");
                return;
            }
        }
        
        
        if(flightList.isEmpty()) {
            JOptionPane.showMessageDialog(null,"No Flight Available");
            
        } 
        populateTable(flightList);
        
        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtDestinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDestinationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDestinationActionPerformed

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed

    private void btnViewBookedTicketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewBookedTicketsActionPerformed
        // TODO add your handling code here:
        ViewTicketJPanel viewPanel = new ViewTicketJPanel(CardSequenceJPanel ,customer,seat);
        CardSequenceJPanel.add("ViewTicketsJPanel", viewPanel);
        CardLayout layout = (CardLayout) CardSequenceJPanel.getLayout();
        layout.next(CardSequenceJPanel);
        
    }//GEN-LAST:event_btnViewBookedTicketsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBookNow;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnViewBookedTickets;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tblFlightDetails;
    private javax.swing.JTextField txtAirliner;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtDestination;
    private javax.swing.JTextField txtFlightNumber;
    private javax.swing.JTextField txtSource;
    // End of variables declaration//GEN-END:variables
}
