package UserInterface.HospitalAdmin;

import UserInterface.DepartmentAdmin.DepartmentInfoJPanel;
import Business.Department.Department;
import Business.Ecosystem;
import Business.Hospital.Hospital;
import Business.Patient.Patient;
import Business.UserAccount.UserAccount;
import UserInterface.Patient.PatientInfoJPanel;
import UserInterface.SystemAdmin.CreateHospitalJPanel;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author riyamoitra
 */
public class HospitalManageDepartmentJPanel extends javax.swing.JPanel {

    JPanel CardLayoutJPanel;
    private Ecosystem business;
    private UserAccount account;
    private Hospital hospital;
    
    /**
     * Creates new form HospitalManageDepartmentJPanel
     */
    

    HospitalManageDepartmentJPanel(JPanel CardLayoutJPanel, UserAccount account, Ecosystem business) {

        initComponents();
        this.CardLayoutJPanel = CardLayoutJPanel;
        this.business= business;
        this.account = account;
        
        hospital= (Hospital) this.account.getDetails();
        
        this.populateTable();
        
    }
    
    public void populateTable() {
        ArrayList<Department> departmentDirectory = hospital.getDepartmentDirectory();
                
        int rowCount = departmentTable.getRowCount();
        DefaultTableModel model = (DefaultTableModel)departmentTable.getModel();
        for(int i=rowCount-1;i>=0;i--) {
            model.removeRow(i);
        }
        
        for(Department dep :  departmentDirectory ) {
            Object row[] = new Object[3];
            row[0] = dep;
            row[1] = dep.getDepartmentName();
            row[2] = dep.getDepartmentAdminName();
            
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        departmentTable = new javax.swing.JTable();
        Viewbtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        Deletebtn = new javax.swing.JButton();
        refreshbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setText("< back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, 40));

        departmentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Department ID", "Department Name", "Department Admin Name"
            }
        ));
        jScrollPane1.setViewportView(departmentTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 110, 700, 156));

        Viewbtn.setText("View Details");
        Viewbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewbtnActionPerformed(evt);
            }
        });
        add(Viewbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 201, -1));

        addBtn.setText("Sign Up New Department");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        Deletebtn.setText("Delete Existing Department");
        Deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletebtnActionPerformed(evt);
            }
        });
        add(Deletebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 201, -1));

        refreshbtn.setText("Refresh");
        refreshbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshbtnActionPerformed(evt);
            }
        });
        add(refreshbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 201, 30));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel1.setText("Pharmacy Portal");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardLayoutJPanel.remove(this);
        CardLayout layout = (CardLayout) CardLayoutJPanel.getLayout();
        layout.previous(CardLayoutJPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
 
        CreateDepartmentJPanel createDepartmentJPanel = new CreateDepartmentJPanel(CardLayoutJPanel, business, hospital);
        CardLayoutJPanel.add("CreateDepartmentJPanel", createDepartmentJPanel);
        CardLayout layout = (CardLayout) CardLayoutJPanel.getLayout();
        layout.next(CardLayoutJPanel);
    }//GEN-LAST:event_addBtnActionPerformed

    private void ViewbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewbtnActionPerformed
        // TODO add your handling code here:
        
        int row = departmentTable.getSelectedRow();
        
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Department viewDepartment = (Department) departmentTable.getValueAt(row, 0);
        
        DepartmentInfoJPanel departmentInfoJPanel = new DepartmentInfoJPanel(CardLayoutJPanel, viewDepartment);
        CardLayoutJPanel.add("DepartmentInfoJPanel", departmentInfoJPanel);
        CardLayout layout = (CardLayout) CardLayoutJPanel.getLayout();
        layout.next(CardLayoutJPanel); 
        
    }//GEN-LAST:event_ViewbtnActionPerformed

    private void DeletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletebtnActionPerformed
        // TODO add your handling code here:
        int row = departmentTable.getSelectedRow();
        Department selected = (Department) departmentTable.getValueAt(row, 0);

        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        hospital.deleteDepartment(selected.getDepartmentId(), business);

        populateTable();
        
        
    }//GEN-LAST:event_DeletebtnActionPerformed

    private void refreshbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshbtnActionPerformed
        // TODO add your handling code here:
        
        populateTable();
        
        
    }//GEN-LAST:event_refreshbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Deletebtn;
    private javax.swing.JButton Viewbtn;
    private javax.swing.JButton addBtn;
    private javax.swing.JButton btnBack;
    private javax.swing.JTable departmentTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshbtn;
    // End of variables declaration//GEN-END:variables

}
