/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemAdmin;

import Business.Ecosystem;
import Business.UserAccount.UserAccount;
import UserInterface.LoginJPanel;
import UserInterface.MainJFrame;
import java.awt.CardLayout;
import static java.time.Clock.system;
import javax.swing.JPanel;
import Business.DB4OUtil.DB4OUtil;

/**
 *
 * @author shivanivats
 */
public class SystemAdminPortalJPanel extends javax.swing.JPanel {

    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    JPanel CardLayoutJPanel;
    UserAccount account;
    Ecosystem business;
    
    /**
     * Creates new form SystemAdminPortalJPanel1
     */
    public SystemAdminPortalJPanel(JPanel CardLayoutJPanel, UserAccount account, Ecosystem ecosystem) {
        initComponents();
        
        this.CardLayoutJPanel = CardLayoutJPanel;
        this.account = account;
        this.business = ecosystem;
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hospitalPortalBtn = new javax.swing.JButton();
        logOutBtn = new javax.swing.JButton();
        patientPortalBtn = new javax.swing.JButton();
        pharmacyBtn = new javax.swing.JButton();
        labbtn = new javax.swing.JButton();
        ambulancebtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        hospitalPortalBtn.setBackground(new java.awt.Color(204, 204, 204));
        hospitalPortalBtn.setText("hospital portal");
        hospitalPortalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospitalPortalBtnActionPerformed(evt);
            }
        });

        logOutBtn.setBackground(new java.awt.Color(204, 204, 204));
        logOutBtn.setText("Logout");
        logOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutBtnActionPerformed(evt);
            }
        });

        patientPortalBtn.setBackground(new java.awt.Color(204, 204, 204));
        patientPortalBtn.setText("patient portal");
        patientPortalBtn.setMaximumSize(new java.awt.Dimension(200, 40));
        patientPortalBtn.setMinimumSize(new java.awt.Dimension(200, 40));
        patientPortalBtn.setPreferredSize(new java.awt.Dimension(200, 40));
        patientPortalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientPortalBtnActionPerformed(evt);
            }
        });

        pharmacyBtn.setBackground(new java.awt.Color(204, 204, 204));
        pharmacyBtn.setText("pharmacy portal");
        pharmacyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pharmacyBtnActionPerformed(evt);
            }
        });

        labbtn.setBackground(new java.awt.Color(204, 204, 204));
        labbtn.setText("Lab Portal");
        labbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labbtnActionPerformed(evt);
            }
        });

        ambulancebtn.setBackground(new java.awt.Color(204, 204, 204));
        ambulancebtn.setText("Ambulance Portal");
        ambulancebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ambulancebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pharmacyBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(patientPortalBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ambulancebtn, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(hospitalPortalBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(logOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(patientPortalBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ambulancebtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hospitalPortalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pharmacyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void patientPortalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientPortalBtnActionPerformed
        // TODO add your handling code here:
        SystemAdminPatientPortalJPanel systemAdminPatientPortalJPanel = new SystemAdminPatientPortalJPanel(CardLayoutJPanel, business);
        CardLayoutJPanel.add("SystemAdminPatientPortalJPanel", systemAdminPatientPortalJPanel);
        CardLayout layout = (CardLayout) CardLayoutJPanel.getLayout();
        layout.next(CardLayoutJPanel);
    }//GEN-LAST:event_patientPortalBtnActionPerformed

    private void hospitalPortalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospitalPortalBtnActionPerformed
        // TODO add your handling code here:
        SystemAdminHospitalPortalJPanel systemAdminHospitalPortalJPanel = new SystemAdminHospitalPortalJPanel(CardLayoutJPanel, business);
        CardLayoutJPanel.add("SystemAdminHospitalPortalJPanel", systemAdminHospitalPortalJPanel);
        CardLayout layout = (CardLayout) CardLayoutJPanel.getLayout();
        layout.next(CardLayoutJPanel); 
    }//GEN-LAST:event_hospitalPortalBtnActionPerformed

    private void logOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBtnActionPerformed
        // TODO add your handling code here:
        dB4OUtil.storeSystem(business);
         LoginJPanel loginJPanel = new LoginJPanel(CardLayoutJPanel, business,"");
        CardLayoutJPanel.add("LoginJPanel", loginJPanel);
        CardLayout layout = (CardLayout) CardLayoutJPanel.getLayout();
        layout.next(CardLayoutJPanel);
        
    }//GEN-LAST:event_logOutBtnActionPerformed

    private void pharmacyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pharmacyBtnActionPerformed
        // TODO add your handling code here:
        SystemAdminPharmacyJPanel systemAdminPharmacyJPanel = new SystemAdminPharmacyJPanel(CardLayoutJPanel, business);
        CardLayoutJPanel.add("SystemAdminPharmacyJPanel", systemAdminPharmacyJPanel);
        CardLayout layout = (CardLayout) CardLayoutJPanel.getLayout();
        layout.next(CardLayoutJPanel); 
    }//GEN-LAST:event_pharmacyBtnActionPerformed

    private void ambulancebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ambulancebtnActionPerformed
        // TODO add your handling code here:
        SystemAdminAmbulanceJPanel systemAdminAmbulanceJPanel = new SystemAdminAmbulanceJPanel(CardLayoutJPanel, business);
        CardLayoutJPanel.add("SystemAdminAmbulanceJPanel", systemAdminAmbulanceJPanel);
        CardLayout layout = (CardLayout) CardLayoutJPanel.getLayout();
        layout.next(CardLayoutJPanel); 
        
    }//GEN-LAST:event_ambulancebtnActionPerformed

    private void labbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labbtnActionPerformed
        // TODO add your handling code here:
        SystemAdminLabJPanel systemAdminLabJPanel = new SystemAdminLabJPanel(CardLayoutJPanel, business);
        CardLayoutJPanel.add("SystemAdminLabJPanel", systemAdminLabJPanel);
        CardLayout layout = (CardLayout) CardLayoutJPanel.getLayout();
        layout.next(CardLayoutJPanel); 
        
    }//GEN-LAST:event_labbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ambulancebtn;
    private javax.swing.JButton hospitalPortalBtn;
    private javax.swing.JButton labbtn;
    private javax.swing.JButton logOutBtn;
    private javax.swing.JButton patientPortalBtn;
    private javax.swing.JButton pharmacyBtn;
    // End of variables declaration//GEN-END:variables
}
