/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemAdmin;

import Business.Appointment.AppointmentSchedule;
import Business.Doctor.DoctorDirectory;
import Business.Ecosystem;
import Business.Hospital.HospitalDirectory;
import Business.Patient.PatientDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Image;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author shivanivats
 */
public class SystemAdminLoginJPanel extends javax.swing.JPanel {
    
    private JPanel CardLayoutJPanel;
    private UserAccount account;
    private Ecosystem business;

    /**
     * Creates new form LoginJPanel
     */
    /**
     * public SystemAdminLoginJPanel(JPanel CardLayoutJPanel) {
        initComponents();
        this.CardLayoutJPanel = CardLayoutJPanel;
        this.ecosystem = ecosystem;
        
//        Image img = ImageIO.read(getClass().getResource("resources/water.bmp"));
//        button.setIcon(new ImageIcon(img));
    }
*/
    public SystemAdminLoginJPanel(JPanel CardLayoutJPanel, UserAccount account, Ecosystem business) {

        initComponents();
        this.CardLayoutJPanel = CardLayoutJPanel;
        this.account=account;
        this.business = business;
    
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        userNametxt = new javax.swing.JTextField();
        loginBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        passwordTxt = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setSize(new java.awt.Dimension(1366, 768));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(153, 255, 255));
        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel3.setText("System Admin Login");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, 390, 50));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Username:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, 100, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel2.setText("Password:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, 110, 20));
        add(usernameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 310, 290, 30));

        loginBtn.setBackground(new java.awt.Color(0, 153, 153));
        loginBtn.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 390, 280, 40));

        backBtn.setBackground(new java.awt.Color(0, 153, 153));
        backBtn.setText("< Main Home Page");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 260, 40));
        add(passwordTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 340, 290, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/SystemAdmin/—Pngtree—blockchain big data mobile phone_920097.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, -110, -1, 870));
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        CardLayoutJPanel.remove(this);
        CardLayout layout = (CardLayout) CardLayoutJPanel.getLayout();
        layout.previous(CardLayoutJPanel);
    }//GEN-LAST:event_backBtnActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        
        String userName = userNametxt.getText();
       // Get Password
       char[] passwordCharArray = passwordtxt.getPassword();
       
       String password = String.valueOf(passwordCharArray);
       
       //Step1: Check in the system admin user account directory if you have the user
       UserAccount account=business.getUserAccountDirectory().authenticateUser(userName, password);
       //JOptionPane.showMessageDialog(null, "Username"+userAccount.getRole().toString());
       if(account != null){
          /**CardLayout layout=(CardLayout)CardLayoutJPanel.getLayout();
            CardLayoutJPanel.add("workArea",userAccount.getRole().createWorkArea(CardLayoutJPanel, account, business,patientDirectory,hospitalDirectory,doctorDirectory,appointmentSchedule));
            layout.next(CardLayoutJPanel);
            */
          
//            SystemAdminPortalJPanel systemAdminPortalJPanel = new SystemAdminPortalJPanel(CardLayoutJPanel);
//            CardLayoutJPanel.add("SystemAdminPortalJPanel", systemAdminPortalJPanel);
//            CardLayout layout = (CardLayout) CardLayoutJPanel.getLayout();
//            layout.next(CardLayoutJPanel);
    }                                  
       
       else{
           JOptionPane.showMessageDialog(null, "Username or password incorrect. Please try again.");
       }
        
        // TODO: Add login validations
      /*  SystemAdminPortalJPanel systemAdminPortalJPanel = new SystemAdminPortalJPanel(CardLayoutJPanel);
        CardLayoutJPanel.add("SystemAdminPortalJPanel", systemAdminPortalJPanel);
        CardLayout layout = (CardLayout) CardLayoutJPanel.getLayout();
        layout.next(CardLayoutJPanel);
*/


    }//GEN-LAST:event_loginBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPasswordField passwordtxt;
    private javax.swing.JTextField userNametxt;
    // End of variables declaration//GEN-END:variables
}
