/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Physician;

import Business.Department.Department;
import Business.Doctor.Doctor;
import Business.Ecosystem;
import Business.Patient.Patient;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author riyamoitra
 */
public class PhysicianInfoJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPhysicianJPanel
     */
    private JPanel CardLayoutJPanel;
    private Doctor doctor;

    public PhysicianInfoJPanel(JPanel CardLayoutJPanel, Doctor viewDoctor) {

        initComponents();
        this.CardLayoutJPanel=CardLayoutJPanel;
        this.doctor= viewDoctor;
     
        emailtxt.setText(doctor.getEmailId());
        contactNumberTxt.setText(doctor.getPhoneNo());
        nameTxt.setText(doctor.getName());
        genderTxt.setText(doctor.getGender());
        licenseTxt.setText(doctor.getLicenseNo());
        deptTxt.setText(doctor.getDepartment().getDepartmentId());
        
        emailtxt.setEnabled(false);
        contactNumberTxt.setEnabled(false);
        nameTxt.setEnabled(false);
        genderTxt.setEnabled(false);
        licenseTxt.setEnabled(false);
        deptTxt.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UpdateBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        genderTxt = new javax.swing.JTextField();
        licenseTxt = new javax.swing.JTextField();
        nameTxt = new javax.swing.JTextField();
        emailtxt = new javax.swing.JTextField();
        contactNumberTxt = new javax.swing.JTextField();
        deptTxt = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UpdateBtn.setText("Update");
        UpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBtnActionPerformed(evt);
            }
        });
        add(UpdateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 335, -1, -1));

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 335, -1, -1));

        backBtn.setText("<back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 18, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("View Physician");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 32, 286, 42));

        jLabel2.setText("Department:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 112, -1, -1));

        jLabel4.setText("Contact Number");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 150, -1, -1));

        jLabel5.setText("Email");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 188, -1, -1));

        jLabel6.setText("Name");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 226, -1, -1));

        jLabel7.setText("License Number");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 264, -1, -1));

        jLabel10.setText("Gender");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 302, -1, -1));
        add(genderTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 297, 157, -1));
        add(licenseTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 259, 157, -1));
        add(nameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 221, 157, -1));

        emailtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailtxtActionPerformed(evt);
            }
        });
        add(emailtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 183, 157, -1));

        contactNumberTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactNumberTxtActionPerformed(evt);
            }
        });
        add(contactNumberTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 145, 157, -1));
        add(deptTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 107, 157, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBtnActionPerformed
        // TODO add your handling code here:

      
        emailtxt.setEnabled(true);
        contactNumberTxt.setEnabled(true);
        nameTxt.setEnabled(true);
        genderTxt.setEnabled(true);
        licenseTxt.setEnabled(true);

        this.saveBtn.setEnabled(true);

        this.UpdateBtn.setEnabled(false);
    }//GEN-LAST:event_UpdateBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:

       
        
        doctor.setEmailId(emailtxt.getText());
        doctor.setPhoneNo(contactNumberTxt.getText());
        doctor.setName(nameTxt.getText());
        doctor.setGender(genderTxt.getText());
        doctor.setLicenseNo(licenseTxt.getText());
        
        emailtxt.setEnabled(false);
        contactNumberTxt.setEnabled(false);
        nameTxt.setEnabled(false);
        genderTxt.setEnabled(false);
        licenseTxt.setEnabled(false);

        this.saveBtn.setEnabled(false);

        this.UpdateBtn.setEnabled(true);

    }//GEN-LAST:event_saveBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        CardLayoutJPanel.remove(this);
        CardLayout layout = (CardLayout) CardLayoutJPanel.getLayout();
        layout.previous(CardLayoutJPanel);
    }//GEN-LAST:event_backBtnActionPerformed

    private void emailtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailtxtActionPerformed

    private void contactNumberTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactNumberTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactNumberTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton UpdateBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField contactNumberTxt;
    private javax.swing.JTextField deptTxt;
    private javax.swing.JTextField emailtxt;
    private javax.swing.JTextField genderTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField licenseTxt;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JButton saveBtn;
    // End of variables declaration//GEN-END:variables
}
